name: push package
on:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker image
        run: |
          docker pull alpine
          docker tag alpine ghcr.io/dwivedine/actorcheck 
          docker push ghcr.io/dwivedine/actorcheck
